import "./globals.css";
import NavComponent from "./ui/navs/NavComponent";
import FooterComponent from "./ui/footers/FooterComponent";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavComponent/>
        {children}
        <FooterComponent/>
      </body>
    </html>
  );
}
