import NavComponent from "./ui/navs/NavComponent";
import FooterComponent from "./ui/footers/FooterComponent";
import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className="d-flex flex-column min-vh-100">
        <NavComponent />
        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
