import './globals.css';
import NavComponent from './ui/navs/NavComponent';
import FooterContact from './ui/footers/FooterComponent';
import { DataProvider } from './contexts/DataContext';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body>
        <header>
          <NavComponent />
        </header>
        <DataProvider>
          <main>
            {children}
          </main>
        </DataProvider>
        <footer>
          <FooterContact />
        </footer>
      </body>
    </html>
  );
}
